services:
  cloudflared:
    image: cloudflare/cloudflared:2026.5.0
    container_name: cloudflared
    restart: unless-stopped
    network_mode: host
    env_file:
      - ./secrets/cloudflared.env
    command: tunnel --no-autoupdate --metrics 127.0.0.1:20241 run
    labels:
      - com.centurylinklabs.watchtower.enable=false
