log:
  level: info

runner:
  file: /data/.runner
  capacity: 2
  timeout: 3h
  shutdown_timeout: 3h
  fetch_timeout: 5s
  fetch_interval: 2s
  report_interval: 1s
  labels:
    - dongwontuna-labs-runner:docker://dongwontuna-labs-runner:latest

cache:
  enabled: true
  dir: /data/.cache/actcache

container:
  docker_host: tcp://docker-in-docker:2375
  force_pull: false
  valid_volumes:
    - /codex-runner-home
    - /codex-runner-locks
