log:
  level: info

runner:
  file: /data/.runner
  capacity: 2
  timeout: 3h
  shutdown_timeout: 3h
  fetch_timeout: 5s
  fetch_interval: 2s
  report_interval: 1s
  labels:
    - ubuntu-latest:docker://node:24-bookworm
    - rust:docker://rust:1-bookworm

cache:
  enabled: true
  dir: /data/.cache/actcache

container:
  docker_host: tcp://docker-in-docker:2375
  force_pull: false

