# >>> forgejo cloudflare access >>>
Host ssh.dongwontuna.net
  User git
  ProxyCommand cloudflared access ssh --hostname %h
  IdentityAgent /home/dongwonttuna/.ssh/agent/forgejo-agent.sock
  IdentitiesOnly yes
  IdentityFile /home/dongwonttuna/.ssh/id_ed25519_github
# <<< forgejo cloudflare access <<<
